// Writes src/app/build-info.ts with the current git sha + build time. Embedded
// at build time, not fetched: a stale cached tab then shows its OWN old stamp.
// The generated file is gitignored.
//
// Docker has no .git in context, so CI passes the commit as GIT_SHA (see
// Dockerfile); local builds fall back to `git`.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'app', 'build-info.ts');

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

// Prefer the CI-provided commit (Docker has no .git); else read it locally.
const envSha = (process.env.GIT_SHA ?? '').slice(0, 7);
const sha = envSha || git('rev-parse --short HEAD') || 'nogit';
// A gitignored build-info.ts won't dirty the tree; any real uncommitted change
// marks the build. (Only meaningful for local builds — Docker has no git.)
const dirty = git('status --porcelain') ? '+' : '';
const builtAt = new Date().toISOString();

writeFileSync(
  out,
  `// Generated by scripts/stamp-version.mjs at build time. Do not edit — gitignored.
export const BUILD_INFO = {
  sha: '${sha}${dirty}',
  builtAt: '${builtAt}',
} as const;
`,
);
console.log(`stamped build-info: ${sha}${dirty} @ ${builtAt}`);
