# hm-agents.nix — home-manager module: life's emotion-suggestion worker (Mac mini).
#
# Apply after editing (it is a PINNED flake input — the lock must be bumped):
#   1. commit this change in ~/Code/life
#   2. cd ~/.config/home-manager
#   3. nix flake update life && home-manager switch --flake .#pippijn
#
# WHY the worker lives on the Mac and dials out: the model is Apple-Silicon MLX,
# and the fleet may not open connections toward this machine (one-way WireGuard
# peer — a compromised server must not reach the archive). So life queues the
# work and this polls for it. See tools/emotion_worker.py.
#
# The model is NOT loaded here. recall's llm-host daemon holds the one copy on
# this Mac (127.0.0.1:8092) and this worker asks it to generate — otherwise the
# machine would hold two 4.3 GB models while also transcribing.
#
# The agent runs a STORE PATH (nix/emotion-worker.nix), not a script in the
# working tree: what launchd runs is then whatever was committed and pinned in
# the flake lock, and an uncommitted edit in ~/Code/life cannot become the
# running daemon. Possible here precisely because the worker imports nothing but
# the standard library — recall's ML agents stay on their uv venv.
#
# Logs go to ~/Library/Logs/life for the same reason: launchd opens the stdio
# paths before any code runs, so a repo that moves or is unreadable takes the
# agent down with an empty log (see recall's exit-78 history).
#
# The token is NOT in the nix store (it would be world-readable there): the
# wrapper reads ~/.config/life/worker.env at runtime, holding
# EMOTION_WORKER_TOKEN=… matching the server's.
#
# home-manager writes each plist read-only into ~/Library/LaunchAgents with no
# native comment, so a provenance `Comment` key points back here. Do NOT
# hand-edit the generated plists.
{ pkgs, ... }:

let
  worker = pkgs.callPackage ../nix/emotion-worker.nix { };
  logs = "/Users/pippijn/Library/Logs/life";
in
{
  # launchd cannot create the log directory — it opens the paths at spawn, and a
  # missing parent is exit 78 with nothing written anywhere.
  home.file."Library/Logs/life/.keep".text = "";

  launchd.agents."org.xinutec.life-emotion-worker" = {
    enable = true;
    config = {
      Label = "org.xinutec.life-emotion-worker";
      Comment =
        "GENERATED by home-manager from life/deploy/hm-agents.nix. Do NOT edit "
        + "this file. To change: edit that module + commit, then in "
        + "~/.config/home-manager run 'nix flake update life && home-manager "
        + "switch --flake .#pippijn'. Runs: nix/emotion-worker.nix.";
      ProgramArguments = [ "${worker}/bin/life-emotion-worker" ];
      RunAtLoad = true;
      KeepAlive = true;
      # Suggestions are never waited on — they are cached and read later — so this
      # yields to anything interactive, including recall's transcription.
      ProcessType = "Background";
      LowPriorityIO = true;
      Nice = 10;
      StandardOutPath = "${logs}/emotion-worker.out.log";
      StandardErrorPath = "${logs}/emotion-worker.err.log";
    };
  };
}
