# home-manager module: life's emotion-suggestion worker and its LLM host on the
# Mac mini.
#
# Apply: commit here, then in ~/.config/home-manager
#   nix flake update life && home-manager switch --flake .#$USER
#
# The model is Apple-Silicon MLX and the fleet cannot dial this Mac (one-way
# WireGuard), so the worker polls life for jobs; see tools/emotion_worker.py.
# Generation goes through the llm-host (llm-host/, 127.0.0.1:8093), the one
# process that holds the model.
#
# The agent runs a store path (nix/emotion-worker.nix; the worker is
# stdlib-only), so only committed, pinned code can become the daemon. Logs go
# to ~/Library/Logs/life: launchd opens stdio before any code runs, and a log
# path inside a moved repo fails silently. The token stays out of the
# world-readable store; the wrapper reads EMOTION_WORKER_TOKEN from
# ~/.config/life/worker.env at runtime.
#
# The generated plists are read-only; their `Comment` key points back here.
{ config, pkgs, life, ... }:

let
  worker = pkgs.callPackage ../nix/emotion-worker.nix { };
  logs = "${config.home.homeDirectory}/Library/Logs/life";

  # The host's env from this flake (uv2nix over llm-host/uv.lock).
  #
  # ⚠ macOS grants /Volumes/Backup access per launchd program, and this wrapper's
  # store path is that program: a change under llm-host/ moves it, and the host
  # then hangs silently on its first weight read until the access is approved
  # again at the Mac.
  llmHost = pkgs.writeShellApplication {
    name = "life-llm-host";
    text = ''
      exec env HF_HOME=${hfHome} ${life.packages.${pkgs.stdenv.hostPlatform.system}.llm-host}/bin/python -m life_llm_host.host
    '';
  };
  # The model cache recall's agents also read, so the weights exist once on disk.
  hfHome = "/Volumes/Backup/cache/cache/huggingface";
in
{
  # launchd cannot create the log directory — it opens the paths at spawn, and a
  # missing parent is exit 78 with nothing written anywhere.
  home.file."Library/Logs/life/.keep".text = "";

  launchd.agents."org.xinutec.life-emotion-worker" = {
    enable = true;
    config = {
      Label = "org.xinutec.life-emotion-worker";
      Comment =
        "GENERATED by home-manager from life/deploy/hm-agents.nix. Do NOT edit "
        + "this file. To change: edit that module + commit, then in "
        + "~/.config/home-manager run 'nix flake update life && home-manager "
        + "switch --flake .#$USER'. Runs: nix/emotion-worker.nix.";
      ProgramArguments = [ "${worker}/bin/life-emotion-worker" ];
      RunAtLoad = true;
      KeepAlive = true;
      # Suggestions are never waited on — they are cached and read later — so this
      # yields to anything interactive, including recall's transcription.
      ProcessType = "Background";
      LowPriorityIO = true;
      Nice = 10;
      StandardOutPath = "${logs}/emotion-worker.out.log";
      StandardErrorPath = "${logs}/emotion-worker.err.log";
    };
  };

  # Holds the ~4.3 GB of weights, loads them on the first request and releases
  # them after five idle minutes (llm-host/src/life_llm_host/host.py).
  #
  # Standard rather than Background: throttled I/O made the cold weight read take
  # 104 s instead of 62 s. Idle, it costs a few MB.
  launchd.agents."org.xinutec.life-llm-host" = {
    enable = true;
    config = {
      Label = "org.xinutec.life-llm-host";
      Comment =
        "GENERATED by home-manager from life/deploy/hm-agents.nix. Do NOT edit "
        + "this file. To change: edit that module + commit, then in "
        + "~/.config/home-manager run 'nix flake update life && home-manager "
        + "switch --flake .#$USER'. Runs: llm-host/.";
      ProgramArguments = [ "${llmHost}/bin/life-llm-host" ];
      RunAtLoad = true;
      KeepAlive = true;
      ProcessType = "Standard";
      StandardOutPath = "${logs}/llm-host.out.log";
      StandardErrorPath = "${logs}/llm-host.err.log";
    };
  };
}
