# hm-agents.nix — home-manager module: life's emotion-suggestion worker (Mac mini).
#
# Apply after editing (it is a PINNED flake input — the lock must be bumped):
#   1. commit this change in ~/Code/life
#   2. cd ~/.config/home-manager
#   3. nix flake update life && home-manager switch --flake .#pippijn
#
# WHY the worker lives on the Mac and dials out: the model is Apple-Silicon MLX,
# and the fleet may not open connections toward this machine (one-way WireGuard
# peer — a compromised server must not reach the archive). So life queues the
# work and this polls for it. See tools/emotion_worker.py.
#
# The model is NOT loaded here. recall's llm-host daemon holds the one copy on
# this Mac (127.0.0.1:8092) and this worker asks it to generate — otherwise the
# machine would hold two 4.3 GB models while also transcribing. So the worker is
# standard-library only; recall's venv is used simply as an interpreter.
#
# The token is NOT in the nix store (it would be world-readable there): the agent
# reads ~/.config/life/worker.env, which is created out of band and holds
# EMOTION_WORKER_TOKEN=… matching the server's.
#
# home-manager writes each plist read-only into ~/Library/LaunchAgents with no
# native comment, so a provenance `Comment` key points back here. Do NOT
# hand-edit the generated plists.
{ ... }:

let
  life = "/Users/pippijn/Code/life";
in
{
  launchd.agents."org.xinutec.life-emotion-worker" = {
    enable = true;
    config = {
      Label = "org.xinutec.life-emotion-worker";
      Comment =
        "GENERATED by home-manager from life/deploy/hm-agents.nix. Do NOT edit "
        + "this file. To change: edit that module + commit, then in "
        + "~/.config/home-manager run 'nix flake update life && home-manager "
        + "switch --flake .#pippijn'. Runs: tools/emotion-worker.sh.";
      ProgramArguments = [ "${life}/tools/emotion-worker.sh" ];
      RunAtLoad = true;
      KeepAlive = true;
      # Suggestions are never waited on — they are cached and read later — so this
      # yields to anything interactive, including recall's transcription.
      ProcessType = "Background";
      LowPriorityIO = true;
      Nice = 10;
      StandardOutPath = "${life}/logs/emotion-worker.out.log";
      StandardErrorPath = "${life}/logs/emotion-worker.err.log";
    };
  };
}
